### PR TITLE
feat: port client from next.js to pure react

### PR DESCRIPTION
**Pull request by luizstacio**
Closes: #14

### CODE REVIEW

**Review by eureka-cpu — APPROVED** [review]
LGTM

**Review by adlerjohn — CHANGES_REQUESTED** [review]
Running `yarn start` gives me a page with

```
Compiled with problems:

ERROR in ./node_modules/@fuel-ts/providers/dist/util.js 18:17-34

Module not found: Error: Can't resolve 'crypto' in '/home/devel/local/fuellabs/swayswap-demo/client/node_modules/@fuel-ts/providers/dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
	- install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "crypto": false }
```

**Comment by luizstacio** [comment]
> Running `yarn start` gives me a page with
> 
> ```
> Compiled with problems:
> 
> ERROR in ./node_modules/@fuel-ts/providers/dist/util.js 18:17-34
> 
> Module not found: Error: Can't resolve 'crypto' in '/home/devel/local/fuellabs/swayswap-demo/client/node_modules/@fuel-ts/providers/dist'
> 
> BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
> This is no longer the case. Verify if you need this module and configure a polyfill for it.
> 
> If you want to include a polyfill, you need to:
> 	- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
> 	- install 'crypto-browserify'
> If you don't want to include a polyfill, you can use an empty module like this:
> 	resolve.fallback: { "crypto": false }
> ```

This was related to this PR: https://github.com/FuelLabs/fuels-ts/pull/151#event-6186218083 will be updating it.

**Review by eureka-cpu — COMMENTED** [review]
ran locally and looks good!

**Review by eureka-cpu — APPROVED** [review]

**Review by adlerjohn — APPROVED** [review]
Runs locally

**Pull request merged**
